TECH_KEYWORDS = [
    "node.js", "express.js", "django", "flask", "ruby on rails", "laravel", "spring boot", "asp.net core", "koa.js", "hapi.js",
    "fastapi", "phoenix elixir", "nestjs", "graphql", "restful api development", "microservices architecture", "serverless architecture",
    "rabbitmq", "kafka", "oauth", "jwt", "authorization", "api gateway", "websockets", "grpc", "sequelize", "typeorm", "hibernate",
    "sql", "mongodb", "cassandra", "couchdb", "postgresql", "mysql", "sqlite", "redis", "elasticsearch", "firebase", "supabase",
    "hasura", "blockchain", "ethereum", "bitcoin", "smart contracts", "solidity", "web3.js", "ethers.js", "truffle", "hardhat",
    "ganache", "metamask", "ipfs", "dapps", "defi", "nfts", "erc20", "erc721", "pow", "pos", "zk proofs", "oracles", "chainlink",
    "the graph", "dao", "governance", "scaling solutions", "baas", "hyperledger", "corda", "polkadot", "solana", "near protocol",
    "aws", "azure", "gcp", "ibm cloud", "oracle cloud", "digitalocean", "heroku", "netlify", "vercel", "docker", "kubernetes",
    "openshift", "jenkins", "gitlab cicd", "circleci", "travis ci", "ansible", "chef", "puppet", "terraform", "cloudformation",
    "helm", "istio", "prometheus", "grafana", "elk stack", "splunk", "new relic", "datadog", "sentry", "nagios", "zabbix", "load balancing",
    "auto scaling", "monitoring", "iac", "configuration management", "cicd", "sre", "devsecops", "network security", "application security",
    "cloud security", "iam", "siem", "ids", "ips", "firewalls", "vpns", "ssltls", "encryption", "pki", "penetration testing", "vulnerability assessment",
    "threat modeling", "risk assessment", "security auditing", "compliance", "soc", "incident response", "digital forensics", "malware analysis",
    "reverse engineering", "ethical hacking", "red teaming", "blue teaming", "owasp top 10", "soar", "python", "r", "pandas", "numpy", "matplotlib",
    "seaborn", "plotly", "scikitlearn", "tensorflow", "pytorch", "keras", "xgboost", "lightgbm", "statsmodels", "nltk", "spacy", "opencv", "dask",
    "apache spark", "hadoop", "hive", "pig", "airflow", "tableau", "power bi", "looker", "superset", "data cleaning", "feature engineering",
    "model deployment", "ab testing", "hypothesis testing", "time series analysis", "classification", "clustering", "pca", "nlp", "computer vision",
    "deep learning", "reinforcement learning", "html5", "css3", "javascript es6", "typescript", "react.js", "angular", "vue.js", "svelte", "jquery",
    "bootstrap", "tailwind css", "materialui", "webpack", "babel", "sassscss", "less", "responsive design", "crossbrowser compatibility",
    "accessibility wcag", "pwa", "ajax", "json", "restful apis", "canvas api", "webrtc", "d3.js", "chart.js", "three.js", "next.js", "nuxt.js",
    "gatsby", "ember.js", "backbone.js", "electron", "cordova", "capacitor", "mern stack", "mean stack", "jamstack", "lamp stack", "t3 stack",
    "devops integration", "cicd pipelines", "nginx", "apache", "rest apis", "serverless functions", "cloud functions", "authentication",
    "testing", "performance optimization", "scalability", "logging", "supervised learning", "unsupervised learning", "semisupervised learning",
    "neural networks", "cnn", "rnn", "lstm", "gan", "transfer learning", "automl", "hyperparameter tuning", "model evaluation", "crossvalidation",
    "biasvariance tradeoff", "overfitting", "underfitting", "feature selection", "model interpretability", "deployment", "mlops", "ml pipelines",
    "dvc", "model monitoring", "edge ai", "federated learning", "explainable ai", "chatbots", "speech recognition", "image recognition", "object detection"
    , "tts", "stt", "nlg", "ner", "sentiment analysis", "topic modeling", "ios", "android", "swift", "objectivec", "kotlin", "java", "react native", "flutter",
    "xamarin", "ionic", "core data", "arkit", "ml kit", "app deployment", "push notifications", "geolocation", "camera integration", "user research", "personas",
    "wireframing", "prototyping", "usability testing", "interaction design", "visual design", "accessibility", "design systems", "figma", "sketch",
    "adobe xd", "invision", "zeplin", "balsamiq", "framer", "photoshop", "illustrator", "motion design", "design thinking", "ux writing", "heatmaps",
    "journey mapping", "branding", "typography", "color theory", "unity", "unreal engine", "c", "game physics", "shader programming", "blender", "3ds max",
    "maya", "godot", "game ai", "multiplayer networking", "photon", "game monetization", "level design", "2d game development", "3d game development",
    "mobile game optimization", "animation", "sprite sheets", "sound design", "vrar development", "uiux for games", "game testing", "asset management",
    "webxr", "aframe", "arcore", "oculus sdk", "hololens", "openxr", "vuforia", "leap motion", "3d modeling", "360 video", "haptics", "gesture recognition",
    "spatial computing", "volumetric video", "embedded c", "arduino", "raspberry pi", "esp32", "rtos", "iot protocols mqtt", "coap", "zigbee", "bluetooth",
    "iot cloud aws iot", "azure iot hub", "microcontrollers", "sensors", "actuators", "pcb design", "firmware development", "iot security", "modbus",
    "can bus", "power optimization", "ros", "gazebo", "openai gym", "lidar", "slam", "navigation", "robot kinematics", "robot operating systems",
    "plc", "scada", "hmi", "labview", "machine vision", "urdf", "simulation", "pid control", "motion planning", "control systems", "assembly",
    "os concepts", "multithreading", "memory management", "pointers", "file systems", "linux kernel", "driver development", "network protocols",
    "concurrency", "interprocess communication", "debugging gdb", "profiling", "makefile", "compilers", "linkers", "system calls", "virtual memory",
    "oracle", "sql server", "data modeling", "normalization", "etl pipelines", "data warehousing", "snowflake", "bigquery", "database tuning", "replication",
    "backup and recovery", "sql optimization", "stored procedures", "indexing", "columnar databases", "data lakes", "manual testing", "automation testing",
    "selenium", "cypress", "junit", "pytest", "testng", "postman", "soapui", "jmeter", "load testing", "regression testing", "unit testing",
    "integration testing", "bug tracking", "jira", "test plans", "test cases", "cicd test automation", "api testing", "crossbrowser testing",
    "test coverage", "mocking", "test data generation", "windows server", "linux", "bash", "powershell", "active directory", "dns", "dhcp",
    "firewall configuration", "vpn", "network troubleshooting", "hardware troubleshooting", "vmware", "hyperv", "patch management", "sccm",
    "itil", "ticketing systems", "network configuration", "email servers", "file sharing", "markdown", "latex", "confluence", "notion", "readme",
    "swagger", "openapi", "uml diagrams", "flowcharts", "version control git", "documentation tools", "user manuals", "api references",
    "release notes", "tutorial writing", "google docs", "asciidoc", "screen recording", "tech blogs", "seo", "sem", "google analytics",
    "google search console", "facebook ads", "google ads", "tag manager", "ahrefs", "semrush", "keyword research", "email marketing", "mailchimp", "crm",
    "content management", "wordpress", "html", "css", "data analytics", "funnel optimization", "meta ads", "marketing automation", "agile", "scrum", "kanban",
    "trello", "monday.com", "risk management", "roadmapping", "stakeholder communication", "product backlog", "gantt charts", "burndown charts", "user stories",
    "requirement gathering", "product analytics", "funnel metrics", "lean", "mvp", "prioritization", "time estimation", "team coordination"
]